// <auto-generated />
namespace JanuszMarcinik.Mvc.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _005_questionnaire_key_type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_005_questionnaire_key_type));
        
        string IMigrationMetadata.Id
        {
            get { return "201710302046535_005_questionnaire_key_type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
