// <auto-generated />
namespace JanuszMarcinik.Mvc.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _003_add_question_categories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_003_add_question_categories));
        
        string IMigrationMetadata.Id
        {
            get { return "201708201212481_003_add_question_categories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
