// <auto-generated />
namespace JanuszMarcinik.Mvc.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _006_scores : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_006_scores));
        
        string IMigrationMetadata.Id
        {
            get { return "201711011515095_006_scores"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
