// <auto-generated />
namespace JanuszMarcinik.Mvc.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _007_remove_description_add_isActive_flag : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_007_remove_description_add_isActive_flag));
        
        string IMigrationMetadata.Id
        {
            get { return "201801151829459_007_remove_description_add_isActive_flag"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
