// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace JanuszMarcinik.Mvc.WebUI.Areas.Application.Controllers
{
    public partial class ResultsController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ResultsController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult Details()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult IntervieweeResults()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IntervieweeResults);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public virtual System.Web.Mvc.ActionResult IntervieweeDetails()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IntervieweeDetails);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ResultsController Actions { get { return MVC.Application.Results; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Application";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Results";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Results";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string General = "General";
            public readonly string Details = "Details";
            public readonly string IntervieweeResults = "IntervieweeResults";
            public readonly string IntervieweeDetails = "IntervieweeDetails";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string General = "General";
            public const string Details = "Details";
            public const string IntervieweeResults = "IntervieweeResults";
            public const string IntervieweeDetails = "IntervieweeDetails";
        }


        static readonly ActionParamsClass_Details s_params_Details = new ActionParamsClass_Details();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Details DetailsParams { get { return s_params_Details; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Details
        {
            public readonly string questionnaireId = "questionnaireId";
        }
        static readonly ActionParamsClass_IntervieweeResults s_params_IntervieweeResults = new ActionParamsClass_IntervieweeResults();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_IntervieweeResults IntervieweeResultsParams { get { return s_params_IntervieweeResults; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_IntervieweeResults
        {
            public readonly string ageId = "ageId";
            public readonly string sexId = "sexId";
            public readonly string educationId = "educationId";
            public readonly string martialStatusId = "martialStatusId";
            public readonly string materialStatusId = "materialStatusId";
            public readonly string placeOfResidenceId = "placeOfResidenceId";
            public readonly string seniorityId = "seniorityId";
        }
        static readonly ActionParamsClass_IntervieweeDetails s_params_IntervieweeDetails = new ActionParamsClass_IntervieweeDetails();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_IntervieweeDetails IntervieweeDetailsParams { get { return s_params_IntervieweeDetails; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_IntervieweeDetails
        {
            public readonly string questionnaireId = "questionnaireId";
            public readonly string ageId = "ageId";
            public readonly string sexId = "sexId";
            public readonly string educationId = "educationId";
            public readonly string martialStatusId = "martialStatusId";
            public readonly string materialStatusId = "materialStatusId";
            public readonly string placeOfResidenceId = "placeOfResidenceId";
            public readonly string seniorityId = "seniorityId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _PearsonCorrelations = "_PearsonCorrelations";
                public readonly string _ResultValue = "_ResultValue";
                public readonly string IntervieweeDetails = "IntervieweeDetails";
                public readonly string IntervieweeResults = "IntervieweeResults";
                public readonly string Results = "Results";
            }
            public readonly string _PearsonCorrelations = "~/Areas/Application/Views/Results/_PearsonCorrelations.cshtml";
            public readonly string _ResultValue = "~/Areas/Application/Views/Results/_ResultValue.cshtml";
            public readonly string IntervieweeDetails = "~/Areas/Application/Views/Results/IntervieweeDetails.cshtml";
            public readonly string IntervieweeResults = "~/Areas/Application/Views/Results/IntervieweeResults.cshtml";
            public readonly string Results = "~/Areas/Application/Views/Results/Results.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_ResultsController : JanuszMarcinik.Mvc.WebUI.Areas.Application.Controllers.ResultsController
    {
        public T4MVC_ResultsController() : base(Dummy.Instance) { }

        [NonAction]
        partial void GeneralOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult General()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.General);
            GeneralOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void DetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int questionnaireId);

        [NonAction]
        public override System.Web.Mvc.ActionResult Details(int questionnaireId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Details);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "questionnaireId", questionnaireId);
            DetailsOverride(callInfo, questionnaireId);
            return callInfo;
        }

        [NonAction]
        partial void IntervieweeResultsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int? ageId, int? sexId, int? educationId, int? martialStatusId, int? materialStatusId, int? placeOfResidenceId, int? seniorityId);

        [NonAction]
        public override System.Web.Mvc.ActionResult IntervieweeResults(int? ageId, int? sexId, int? educationId, int? martialStatusId, int? materialStatusId, int? placeOfResidenceId, int? seniorityId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IntervieweeResults);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ageId", ageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sexId", sexId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "educationId", educationId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "martialStatusId", martialStatusId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "materialStatusId", materialStatusId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "placeOfResidenceId", placeOfResidenceId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "seniorityId", seniorityId);
            IntervieweeResultsOverride(callInfo, ageId, sexId, educationId, martialStatusId, materialStatusId, placeOfResidenceId, seniorityId);
            return callInfo;
        }

        [NonAction]
        partial void IntervieweeDetailsOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, int questionnaireId, int? ageId, int? sexId, int? educationId, int? martialStatusId, int? materialStatusId, int? placeOfResidenceId, int? seniorityId);

        [NonAction]
        public override System.Web.Mvc.ActionResult IntervieweeDetails(int questionnaireId, int? ageId, int? sexId, int? educationId, int? martialStatusId, int? materialStatusId, int? placeOfResidenceId, int? seniorityId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IntervieweeDetails);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "questionnaireId", questionnaireId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "ageId", ageId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "sexId", sexId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "educationId", educationId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "martialStatusId", martialStatusId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "materialStatusId", materialStatusId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "placeOfResidenceId", placeOfResidenceId);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "seniorityId", seniorityId);
            IntervieweeDetailsOverride(callInfo, questionnaireId, ageId, sexId, educationId, martialStatusId, materialStatusId, placeOfResidenceId, seniorityId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
