// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments and CLS compliance
// 0108: suppress "Foo hides inherited member Foo. Use the new keyword if hiding was intended." when a controller and its abstract parent are both processed
// 0114: suppress "Foo.BarController.Baz()' hides inherited member 'Qux.BarController.Baz()'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword." when an action (with an argument) overrides an action in a parent controller
#pragma warning disable 1591, 3008, 3009, 0108, 0114
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Threading.Tasks;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace JanuszMarcinik.Mvc.WebUI.Areas.Application.Controllers
{
    public partial class SurveyController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected SurveyController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(Task<ActionResult> taskResult)
        {
            return RedirectToAction(taskResult.Result);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(Task<ActionResult> taskResult)
        {
            return RedirectToActionPermanent(taskResult.Result);
        }


        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public SurveyController Actions { get { return MVC.Application.Survey; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "Application";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Survey";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Survey";
        [GeneratedCode("T4MVC", "2.0")]
        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string IntervieweeInfo = "IntervieweeInfo";
            public readonly string LOT = "LOT";
            public readonly string IZZ = "IZZ";
            public readonly string WHOQOL = "WHOQOL";
            public readonly string ThankYou = "ThankYou";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string IntervieweeInfo = "IntervieweeInfo";
            public const string LOT = "LOT";
            public const string IZZ = "IZZ";
            public const string WHOQOL = "WHOQOL";
            public const string ThankYou = "ThankYou";
        }


        static readonly ActionParamsClass_IntervieweeInfo s_params_IntervieweeInfo = new ActionParamsClass_IntervieweeInfo();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_IntervieweeInfo IntervieweeInfoParams { get { return s_params_IntervieweeInfo; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_IntervieweeInfo
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_LOT s_params_LOT = new ActionParamsClass_LOT();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_LOT LOTParams { get { return s_params_LOT; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_LOT
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_IZZ s_params_IZZ = new ActionParamsClass_IZZ();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_IZZ IZZParams { get { return s_params_IZZ; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_IZZ
        {
            public readonly string model = "model";
        }
        static readonly ActionParamsClass_WHOQOL s_params_WHOQOL = new ActionParamsClass_WHOQOL();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_WHOQOL WHOQOLParams { get { return s_params_WHOQOL; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_WHOQOL
        {
            public readonly string model = "model";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _WHOQOL_PartTable = "_WHOQOL_PartTable";
                public readonly string IntervieweeInfo = "IntervieweeInfo";
                public readonly string IZZ = "IZZ";
                public readonly string LOT = "LOT";
                public readonly string ThankYou = "ThankYou";
                public readonly string WHOQOL = "WHOQOL";
            }
            public readonly string _WHOQOL_PartTable = "~/Areas/Application/Views/Survey/_WHOQOL_PartTable.cshtml";
            public readonly string IntervieweeInfo = "~/Areas/Application/Views/Survey/IntervieweeInfo.cshtml";
            public readonly string IZZ = "~/Areas/Application/Views/Survey/IZZ.cshtml";
            public readonly string LOT = "~/Areas/Application/Views/Survey/LOT.cshtml";
            public readonly string ThankYou = "~/Areas/Application/Views/Survey/ThankYou.cshtml";
            public readonly string WHOQOL = "~/Areas/Application/Views/Survey/WHOQOL.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public partial class T4MVC_SurveyController : JanuszMarcinik.Mvc.WebUI.Areas.Application.Controllers.SurveyController
    {
        public T4MVC_SurveyController() : base(Dummy.Instance) { }

        [NonAction]
        partial void IntervieweeInfoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult IntervieweeInfo()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IntervieweeInfo);
            IntervieweeInfoOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void IntervieweeInfoOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, JanuszMarcinik.Mvc.WebUI.Areas.Admin.Models.Interviewees.IntervieweeViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult IntervieweeInfo(JanuszMarcinik.Mvc.WebUI.Areas.Admin.Models.Interviewees.IntervieweeViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IntervieweeInfo);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            IntervieweeInfoOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void LOTOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult LOT()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LOT);
            LOTOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void LOTOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, JanuszMarcinik.Mvc.WebUI.Areas.Application.Models.Survey.LOTViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult LOT(JanuszMarcinik.Mvc.WebUI.Areas.Application.Models.Survey.LOTViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.LOT);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            LOTOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void IZZOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult IZZ()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IZZ);
            IZZOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void IZZOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, JanuszMarcinik.Mvc.WebUI.Areas.Application.Models.Survey.IZZViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult IZZ(JanuszMarcinik.Mvc.WebUI.Areas.Application.Models.Survey.IZZViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.IZZ);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            IZZOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void WHOQOLOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult WHOQOL()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.WHOQOL);
            WHOQOLOverride(callInfo);
            return callInfo;
        }

        [NonAction]
        partial void WHOQOLOverride(T4MVC_System_Web_Mvc_ActionResult callInfo, JanuszMarcinik.Mvc.WebUI.Areas.Application.Models.Survey.WHOQOLViewModel model);

        [NonAction]
        public override System.Web.Mvc.ActionResult WHOQOL(JanuszMarcinik.Mvc.WebUI.Areas.Application.Models.Survey.WHOQOLViewModel model)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.WHOQOL);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "model", model);
            WHOQOLOverride(callInfo, model);
            return callInfo;
        }

        [NonAction]
        partial void ThankYouOverride(T4MVC_System_Web_Mvc_ActionResult callInfo);

        [NonAction]
        public override System.Web.Mvc.ActionResult ThankYou()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ThankYou);
            ThankYouOverride(callInfo);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591, 3008, 3009, 0108, 0114
